### PR TITLE
passing the args into a dictionary for easy forwarding of args

### PR DESCRIPTION
**Pull request by tokejepsen**

### CODE REVIEW

**Comment by mottosso** [comment]
What is `args`? It looks like only key/value pairs passed to `-data`.

``` python
{
  "key1": "value1"
}
```

Shouldn't it be this?

``` python
{
  "data": {
    "key1": "value1"
  }
}
```

Also keep in mind that the single `-` is by convention reserved for short arguments, e.g. `-d`, versus double `--` which is for optional arguments. So it should really be `--data`.

**Comment by tokejepsen** [comment]
I guess it would make sense to make it into a dictionary of dictionaries. Although would you continue to pass the key and values into the context?

If the package only takes one set of data `--data` then having it as a subset of dictionaries, doesn't make much sense.

**Comment by mottosso** [comment]
It might end up taking more arguments. The Pyblish CLI takes many arguments, for example `--path` to pass a custom plug-in path.

The dictionary might end up like this.

``` json
{
  "data": {"key": "value"},
  "paths": ["c:\\custom\\path"],
  "otherkey": "othervalue"
}
```

And so forth. The premise being that you are passing key/value pairs from the command line, and if you are going to store them anywhere, they should probably remain key/value pairs, and `data` itself is a dictionary.

Also, I think "kwargs" is better suited, as it is key-word arguments. "args" sounds like a list.

``` python
context.set_data("kwargs", kwargs)
```

**Comment by tokejepsen** [comment]
Updated the PR

**Comment by mottosso** [comment]
Great work, should I merge?

**Comment by tokejepsen** [comment]
why not:)

**Pull request merged**
