### PR TITLE
Implementing Argparse and Automatic shutdown on completion

### PR DESCRIPTION
**Pull request by mottosso**
@tokejepsen I wasn't sure what command-line arguments you were using, it looks like you implemented in such a way that you could pass any argument.

I've only added `--data`, let me know if there's anything else you use.

Other than that, I've also moved the CLI to **main**, such that you can get help from the command-line when using it.

``` bash
SYSTEM@ALIENFX>python -m pyblish_standalone --help
usage: __main__.py [-h] [-d key value]

optional arguments:
  -h, --help            show this help message and exit
  -d key value, --data key value
                        Append data to context

SYSTEM@ALIENFX>
```

And here's how I'm assuming you are already using `--data`

``` bash
python -m pyblish_standalone --data mykey myvalue --data myotherkey 5
```

Let me know if what you think.

Implements #3

### CODE REVIEW

**Comment by tokejepsen** [comment]
Its not quite how I'm currently using it, but I can easily change it.

There are two major differences, which is that with the current version you can pass in arguments that will turn into dictionaries and lists, as well as direct keys.

```
python -m pyblish_standalone --data mykey myvalue --data myotherkey 5 --somekey somevalue --somelist value1 value2 value3
```

```
kwargs = {'data': {'mykey': 'myvalue', 'myotherkey': '5'}, 'somekey': 'somevalue', 'somelist': [value1, value2, value3]}
```

Is this possible with ArgParse?

**Comment by mottosso** [comment]
> Is this possible with ArgParse?

It's possible, but it isn't terribly command-line friendly. Ideally we would register the exact arguments that are available.

Which other arguments are you looking for? Could they not also go into `data`?

**Comment by tokejepsen** [comment]
> Which other arguments are you looking for? Could they not also go into data?

Sure I don't mind. Just thought that was what you were after here; https://github.com/pyblish/pyblish-standalone/pull/2#issuecomment-130342150

**Comment by mottosso** [comment]
Yeah, in that case, we would add `paths` and `otherkey` as arguments.

``` bash
pyblish_standalone --paths "c:\mypath" --otherkey 5
```

`paths` in particlar, as it's an existing argument with the vanilla Pyblish CLI.

The benefit of this approach is that it's a familiar CLI interface, and that it provides an automatic help page `--h` for those who don't know of all of the options.

Could you give it a try and see if the automatic shutdown works for your use cases? Especially when launching from ftrack. Basically, once you hit enter in the terminal, the GUI shuts down, like if you had pressed the X button on the window (without shift).

**Comment by tokejepsen** [comment]
> Basically, once you hit enter in the terminal, the GUI shuts down, like if you had pressed the X button on the window (without shift).

What is the difference between this automatic shutdown and just closing the GUI and the terminal?

**Comment by mottosso** [comment]
When you hit enter in the terminal previously, the GUI would end up in an inconsistent state, as it would try and read from the process you just closed. When you try and refresh, it basically hangs for a few seconds, until it's own terminal spits out "connection refused".

This way, that is less likely to happen.

To fool proof it, I think it should also close the GUI when you _close_ the terminal, and probably close the terminal when you close the GUI, as they are dependent on each other anyway.

**Comment by tokejepsen** [comment]
> To fool proof it, I think it should also close the GUI when you close the terminal, and probably close the terminal when you close the GUI, as they are dependent on each other anyway.

Think this is probably the most likely use case for artists. They will just hit the "X" button to close.

**Comment by mottosso** [comment]
Yeah, makes sense. You mean the X on the Pyblish window right?

It's tricky, because the same window could be used from another host, without closing it. Hitting the X on the terminal window on the other hand would work, but it would mean there has to be two windows, both a terminal and the Pyblish window. Not very intuitive.

**Comment by tokejepsen** [comment]
> It's tricky, because the same window could be used from another host, without closing it. Hitting the X on the terminal window on the other hand would work, but it would mean there has to be two windows, both a terminal and the Pyblish window. Not very intuitive.

I guess you are right about the intuitiveness, but can't see what the alternative is.

**Comment by mottosso** [comment]
> but can't see what the alternative is.

Me neither. :( Will have to think about it.

We could run QML on it's own process; quitting it would quit everything. The downside being start-up time cost.

**Comment by tokejepsen** [comment]
> The downside being start-up time cost.

I was going to make an issue about this, as I think its a bit slow atm. Adding this on top, would just further annoy the artists.

**Comment by mottosso** [comment]
> I was going to make an issue about this

Yes, let's make a new issue about it. I have a few questions about this.

**Comment by tokejepsen** [comment]
I think we should have an optional "host" argument.

**Comment by tokejepsen** [comment]
Scrap that about the "host" argument. I can use it for After Effects, so I'll stick with registering the host in a plugin.

**Comment by mottosso** [comment]
> registering the host in a plugin.

Interesting idea, taking advantage of the dynamic nature of Python. Let me know how that goes!

**Comment by mottosso** [comment]
Hey @tokejepsen, I've made some additions and was planning on merging.

Could you let me know if this works for you? You can pull from https://github.com/mottosso/pyblish-standalone.git to try it out.

**Comment by tokejepsen** [comment]
How come the data is a list of lists?

Wouldn't it be better to have a dictionary.

Current:
`{'data': [['scene', 'some/path']]}`
Suggested:
`{'data': {'scene': 'some/path}}`

Or is this the responsibility of a custom plugin?

**Comment by mottosso** [comment]
I know what you mean, it's currently included as a direct result of `argparse`. That's just how it chooses to handle these kind of arguments.

We could make it a dictionary, I don't see why not.

**Comment by mottosso** [comment]
Actually now that I think of it, it does limit the ability to pass arguments with the same key.

``` bash
$ pyblish_standalone --data key Value1 --data key Value2
```

But seeing as data is meant to end up in a dictionary anyway, I think it's safe to discard.

**Comment by tokejepsen** [comment]
It works, but getting a `'list' object has no attribute 'iteritems'` error on line 14 in `collect_data.py`

**Comment by tokejepsen** [comment]
```
C:\Program Files (x86)\CelAction>"K:\development\tools\pyblish\\pyblish-win\bin\
python.bat" -m pyblish_standalone -d settings .\.ini -d scene O:/episodes/test/f
armsong/sh010/animation/sh010.animation.v001.scn -d title New -d chunk 100 -d st
art 1 -d end 1 -d x 1024 -d y 576
```

**Comment by mottosso** [comment]
Should be fixed now.

**Comment by tokejepsen** [comment]
Works in After Effects and CelAction. Safe to merge:)

**Comment by mottosso** [comment]
Cool, added a small bugfix too.

**Pull request merged**
